CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('companies/', include('companies.urls', namespace= 'companies')),
    path('', include('employees.urls')),
    path('contact/', include(('contacts.urls', 'contacts'), namespace='contacts')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

companies/urls.py
from django.urls import path
from . import views


app_name = 'companies'

urlpatterns = [
    path('detail/<int:pk>/', views.company_detail, name='company_detail'),
    path('add/',views.add_company, name='add_company' ),
    path('edit/<int:company_id>/',views.edit_company, name='edit_company' ),
    path('list/', views.company_list, name='company_list'),
]

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('contact/<int:company_id>/', views.contact_detail, name='contact_detail'),
    path('add-contact/<int:pk>/',views.add_contact, name='add_contact' ),
    path('edit/<int:contact_id>/',views.edit_contact, name='edit_contact'),
    path('contact-list/', views.contact_list, name='contact_list'),
    path('list/', views.list, name='list'),
]

employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('login', views.signin, name='login'),
    path("logout", views.signoff, name="logout"),
    path('employee/create/', views.create_employee, name='create_employee'),
    path('employee/list/', views.employee_list, name='employee_list'),
]

companies/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=255)
    industry = models.CharField(max_length=255)
    website = models.URLField(max_length=200, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=100, blank=True)
    notes = models.TextField(blank=True)
    
    def __str__(self):
        return self.name

companies/forms.py
from django import forms
from .models import Company

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

companies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CompanyForm
from .models import Company
from contacts.models import Contact
from interactions.models import Interaction
from .serializers import CompanySerializer
from contacts.serializers import ContactSerializer
from interactions.serializers import InteractionSerializer
from django.contrib.auth.decorators import login_required

@login_required
def company_list(request):
    companies = Company.objects.all()
    return render(request, 'companies/company_list.html', {'companies': companies})

@login_required
def company_detail(request, pk):
    instance = Company.objects.get(pk=pk)
    instances = Contact.objects.filter(pk=pk)
    instancess = Interaction.objects.filter(pk=pk)
    serializer = CompanySerializer(instance)
    serializers = ContactSerializer(instances, many = True)
    serializerss = InteractionSerializer(instancess, many = True)
    return render(request, 'companies/company_detail.html', {'serializer_data': serializer.data,'serializers_data': serializers.data ,'serializerss_data': serializerss.data })


@login_required
def add_company(request):
    if request.method == 'POST':
        data = request.POST
        serializer = CompanySerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return redirect('/companies/list')
    else:
        serializer = CompanySerializer()

    return render(request, 'companies/add_company.html', {'serializer': serializer})


@login_required
def edit_company(request, company_id):
    company = get_object_or_404(Company, pk=company_id)

    if request.method == 'POST':
        data = request.POST
        serializer = CompanySerializer(instance=company, data=data)
        if serializer.is_valid():
            serializer.save()
            return redirect('/companies/list')
    else:
        serializer = CompanySerializer(instance=company)

    return render(request, 'companies/add_company.html', {'serializer_data': serializer.data, 'company': company, 'editing': True})

companies/templates/companies/add_company.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% if editing %}Edit{% else %}Add{% endif %} Company</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    
</head>
<body>
    
    <div id= "main" ,class="container-fluid">
        {% include 'companies/nav-bar.html' %}
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 main-content">
                <div class="container">
                <h1>{% if editing %}Edit{% else %}Add{% endif %} Company</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" required placeholder="Company Name" value="{% if editing %}{{  serializer_data.name }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="industry">Industry</label>
                        <input type="text" class="form-control" id="industry" name="industry" required placeholder="Industry" value="{% if editing %}{{  serializer_data.industry }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input type="url" class="form-control" id="website" name="website" placeholder="Website URL" value="{% if editing %}{{  serializer_data.website }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="phone_number">Phone Number</label>
                        <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="Phone Number" value="{% if editing %}{{  serializer_data.phone_number }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" id="address" name="address" placeholder="Address" value="{% if editing %}{{  serializer_data.address }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" class="form-control" id="city" name="city" placeholder="City" value="{% if editing %}{{  serializer_data.city }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="state">State</label>
                        <input type="text" class="form-control" id="state" name="state" placeholder="State" value="{% if editing %}{{  serializer_data.state }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="postal_code">Postal Code</label>
                        <input type="text" class="form-control" id="postal_code" name="postal_code" placeholder="Postal Code" value="{% if editing %}{{  serializer_data.postal_code }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="country">Country</label>
                        <input type="text" class="form-control" id="country" name="country" placeholder="Country" value="{% if editing %}{{  serializer_data.country }}{% endif %}">
                    </div>
                    <div class="form-group">
                        <label for="notes">Notes</label>
                        <textarea class="form-control" id="notes" name="notes" rows="4" placeholder="Notes">{% if editing %}{{  serializer_data.notes }}{% endif %}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </main>
    </div>

    <div class="modal fade" id="addContactModal" tabindex="-1" aria-labelledby="addContactModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
</body>
<!-- jQuery and Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</html>

companies/templates/companies/company_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Company Detail</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% include 'companies/nav-bar.html' %}

    <h1>Company Detail</h1>
    <div class="container-fluid">
        <div class="card-body">
            <h2>Company Data</h2>
            <ul>
                <li><strong>Name:</strong> {{ serializer_data.name }}</li>
                <li><strong>Industry:</strong> {{ serializer_data.industry }}</li>
                <li><strong>Website:</strong> {{ serializer_data.website }}</li>
                <li><strong>Phone Number:</strong> {{ serializer_data.phone_number }}</li>
                <li><strong>Address:</strong> {{ serializer_data.address }}</li>
                <li><strong>City:</strong> {{ serializer_data.city }}</li>
                <li><strong>State:</strong> {{ serializer_data.state }}</li>
                <li><strong>Postal Code:</strong> {{ serializer_data.postal_code }}</li>
                <li><strong>Country:</strong> {{ serializer_data.country }}</li>
                <li><strong>Notes:</strong> {{ serializer_data.notes }}</li>
            </ul>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-body">
            {%for contact in serializers_data%}
            <h5 class="card-title">{{ contact.first_name }} {{ contact.last_name }}</h5>
            <p class="card-text">Email: {{ contact.email }}</p>
            <p class="card-text">Phone Number: {{ contact.phone_number }}</p>
            <p class="card-text">Job Title: {{ contact.job_title }}</p>
            <p class="card-text">Department: {{ contact.department }}</p>
            <p class="card-text">Notes: {{ contact.notes }}</p>
            {%endfor%}
        </div>
    </div>
    <div class="container mt-5">
        <h1>Interaction Detail</h1>
        <div class="card">
            <div class="card-body">
                <h2>Interaction Data</h2>
                {%for serializer_datas in serializerss_data%}
                <ul>
                    <li><strong>Interaction Date:</strong> {{ serializer_datas.interaction_date}}</li>
                    <li><strong>Call Status:</strong> {{ serializer_datas.call_status }}</li>
                    <li><strong>Call Notes:</strong> {{ serializer_datas.call_notes }}</li>
                </ul>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

companies/templates/companies/company_list.html
{% load static %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Company List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    {% include 'companies/nav-bar.html' %}
    
    <div id= "main" ,class="container-fluid">
        <div class="row">
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 main-content">
                <div class="container">
                    <h1 class="mt-4">Companies</h1>
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>Name</th>
                                <th>Industry</th>
                                <th>Website</th>
                                <th>Contact</th>
                                <th>Address</th>
                                <th>City</th>
                                <th>State</th>
                                <th>Postal Code</th>
                                <th>Country</th>
                                <th>Actions</th>
                                <th>contact</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for company in companies %}
                                <tr>
                                    <td>{{ company.name }}</td>
                                    <td>{{ company.industry }}</td>
                                    <td>{{ company.website }}</td>
                                    <td>{{ company.phone_number }}</td>
                                    <td>{{ company.address }}</td>
                                    <td>{{ company.city }}</td>
                                    <td>{{ company.state }}</td>
                                    <td>{{ company.postal_code }}</td>
                                    <td>{{ company.country }}</td>
                                    <td>
                                        <a href="{% url 'companies:edit_company' company.id %}" class="btn btn-primary"><i class="bi bi-pencil-square"></i></a>
                                    </td>
                                    <td>
                                        <a href="{% url 'contacts:add_contact' company.id %}" class="btn btn-primary"><i class="bi bi-plus-square"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </main>
        </div>
    </div>
</body>
</html>

companies/templates/companies/nav-bar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Your Page Title</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        body {
            font-family: "Lato", sans-serif;
            transition: background-color .5s;
            margin: 0;
        }

        #navbar {
            background-color: #333;
            padding: 10px;
            color: white;
            text-align: left;
            position: fixed;
            width: 100%;
            z-index: 999;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        #navbar a {
            color: white;
            text-decoration: none;
            margin-left: 20px;
        }


        .overlay {
            position: fixed;
            width: 100vw;
            height: 100vh;
            background: rgba(0, 0, 0, 0.7);
            z-index: 998;
            display: none;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

        .sidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .sidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        .sidenav img {
            width: 80%;
            margin: 20px 0;
        }

        @media screen and (max-height: 450px) {
            .sidenav {padding-top: 15px;}
            .sidenav a {font-size: 18px;}
        }
    </style>
</head>
<body>
<div id="navbar" class="navbar">
    
    <div>
        <button onclick="toggleNav()"> <span style="font-size:15px;cursor:pointer" >&#9776; </span></button>
    </div>
    <div>
        <a href="{% url 'employees:logout' %}">Logout</a> 
    </div>
</div> 

<div id="mySidenav" class="sidenav">
    <img src="{% static 'images/icons8-crm-64.png' %}" alt="Logo">
  
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'companies:company_list' %}">Companies</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'companies:add_company' %}">Add Company</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts:contact_list' %}">Contacts</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts:list' %}">List</a>
        </li>
    </ul>
</div>


<script>
    var menuState = 1;

    function toggleNav() {
        var mySidenav = document.getElementById("mySidenav");
        var mainContent = document.getElementById("main");
    
        if (menuState === 1) {
            menuState = 0;
            mySidenav.style.width = "0";
            mainContent.style.marginLeft = "0";
        } else {
            menuState = 1;
            mySidenav.style.width = "250px";
            mainContent.style.marginLeft = "250px";
            document.body.style.backgroundColor = "white";
        }
    }
    
</script>
   
</body>
</html>