CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('companies/', include('companies.urls', namespace= 'companies')),
    path('', include('employees.urls')),
    path('contact/', include(('contacts.urls', 'contacts'), namespace='contacts')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('contact/<int:company_id>/', views.contact_detail, name='contact_detail'),
    path('add-contact/<int:pk>/',views.add_contact, name='add_contact' ),
    path('edit/<int:contact_id>/',views.edit_contact, name='edit_contact'),
    path('contact-list/', views.contact_list, name='contact_list'),
    path('list/', views.list, name='list'),
]

contacts/models.py
from django.db import models
from companies.models import Company

# Create your models here.



class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    job_title = models.CharField(max_length=100, blank=True)
    department = models.CharField(max_length=100, blank=True)
    notes = models.TextField(blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank= True)


    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    

contacts/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

contacts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django_tables2 import RequestConfig
from .models import Contact, Company
from .forms import ContactForm
from .serializers import ContactSerializer
from .tables import ContactTable
from django.contrib.auth.decorators import login_required

@login_required
def contact_list(request):
    contact = Contact.objects.all()
    return render(request, 'contacts/contact_list.html', {'contact': contact})

@login_required
def contact_detail(request, company_id):
    # contact_id = get_object_or_404(Contact, id=company_id)
    instance = Contact.objects.filter(company_id=company_id)
    serializer = ContactSerializer(instance, many=True)
    return render(request, 'contacts/contact_detail.html', {'serializer_data': serializer.data})

@login_required
def add_contact(request, pk):
    company = get_object_or_404(Company, pk=pk)

    if request.method == 'POST':
        data = request.POST
        serializer = ContactSerializer(data=data)
        if serializer.is_valid():
            serializer.validated_data['company'] = company
            serializer.save()
            return redirect('contacts:list')
    else:
        serializer = ContactSerializer()

    companies = Company.objects.all()

    return render(request, 'contacts/add_contact.html', {'serializer': serializer, 'companies': companies, 'selected_company': company})

@login_required
def edit_contact(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)

    if request.method == 'POST':
        data = request.POST
        serializer = ContactSerializer(instance=contact, data=data)
        if serializer.is_valid():
            serializer.save()
            return redirect('contacts:contact_list')
        else:
            print(serializer.errors)
    else:
        serializer = ContactSerializer(instance=contact)

    companies = Company.objects.all() 

    return render(request, 'contacts/add_contact.html', {'serializer_data': serializer.data, 'companies': companies, 'editing': True, 'contact_id': contact_id})

@login_required
def list(request):
    queryset = Contact.objects.all()
    table = ContactTable(queryset)
    RequestConfig(request).configure(table)
    return render(request, 'contacts/list.html', {'table': table})

contacts/templates/contacts/add_contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Contact</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
    <div id= "main" ,class="container-fluid">
    {% include 'companies/nav-bar.html' %}
       <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 main-content">   
           <div class="container">
            <h1>{% if editing %}Edit{% else %}Add{% endif %} Contact</h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="first_name">First Name</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" value="{% if editing %}{{  serializer_data.first_name }}{% endif %}" required>
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" value="{% if editing %}{{  serializer_data.last_name }}{% endif %}" required>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{% if editing %}{{  serializer_data.email }}{% endif %}">
                </div>
                <div class="form-group">
                    <label for="phone_number">Phone Number</label>
                    <input type="text" class="form-control" id="phone_number" name="phone_number" value="{% if editing %}{{  serializer_data.phone_number }}{% endif %}">
                </div>
                <div class="form-group">
                    <label for="job_title">Job Title</label>
                    <input type="text" class="form-control" id="job_title" name="job_title" value="{% if editing %}{{  serializer_data.job_title }}{% endif %}">
                </div>
                <div class="form-group">
                    <label for="department">Department</label>
                    <input type="text" class="form-control" id="department" name="department" value="{% if editing %}{{  serializer_data.department }}{% endif %}">
                </div>
                {% comment %} <div class="form-group">
                    <label for="company">Company</label>
                    <select class="form-control" id="company" name="company">
                        <option value="">Select a Company</option>
                        {% for company in companies %}
                            <option value="{{ company.id }}" {% if editing and company_id == serializer_data.company_id %}selected{% endif %}>
                                {{ company.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div> {% endcomment %}
                
                <div class="form-group">
                    <label for="notes">Notes</label>
                    <textarea class="form-control" id="notes" name="notes" rows="4" value="{% if editing %}{{  serializer_data.notes }}{% endif %}"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    
        
        <div class="modal fade" id="addContactModal" tabindex="-1" aria-labelledby="addContactModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
</body>
</html>

contacts/templates/contacts/contact_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Detail</title>
    <!-- Add Bootstrap CSS here or link to a Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
    <div id= "main" ,class="container-fluid">
        {% include 'companies/nav-bar.html' %}
        <h1 class="mt-5">Contact Detail</h1>
        
        <div class="card mt-3">
            <div class="card-body">
                {%for contact in serializer_data%}
                <h5 class="card-title">{{ contact.first_name }} {{ contact.last_name }}</h5>
                <p class="card-text">Email: {{ contact.email }}</p>
                <p class="card-text">Phone Number: {{ contact.phone_number }}</p>
                <p class="card-text">Job Title: {{ contact.job_title }}</p>
                <p class="card-text">Department: {{ contact.department }}</p>
                <p class="card-text">Notes: {{ contact.notes }}</p>
                {%endfor%}
            </div>
        </div>
        
        <a class="btn btn-primary mt-3" href="{% url 'contacts:contact_list' %}">Back to Contact List</a>
    </div>
</body>
</html>

contacts/templates/contacts/contact_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact List</title>
    <!-- Add Bootstrap CSS here or link to a Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
    <div id= "main" ,class="container-fluid">
        {% include 'companies/nav-bar.html' %}
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 main-content">
                <div class="container">
        <h1 class="mt-5">Contact List</h1>
        
        <table class="table table-bordered mt-3">
            <thead class="thead-dark">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Job Title</th>
                    <th>Department</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in contact%}
                    <tr>
                        <td>{{ contact.first_name }}</td>
                        <td>{{ contact.last_name }}</td>
                        <td>{{ contact.email }}</td>
                        <td>{{ contact.phone_number }}</td>
                        <td>{{ contact.job_title }}</td>
                        <td>{{ contact.department }}</td>
                        <td>
                            <a href="{% url 'contacts:edit_contact' contact.id %}" class="btn btn-primary">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
        {% comment %} <a class="btn btn-primary" href="{% url 'add_contact' %}">Add Contact</a> {% endcomment %}
    </div>
</body>
</html>

contacts/templates/contacts/list.html
{% load static %}
{% load render_table from django_tables2 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div id="main" class="container-fluid">
        {% include 'companies/nav-bar.html' %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 main-content">
            <div class="container">
                <h1>List</h1>
                <div class="table-responsive">
                    {% render_table table %}
                </div>
            </div>
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>